/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_DRIVE_B_FILES           10
#define MMAP_DRIVE_B_CHECKSUM        0xDE7A

enum MMAP_DRIVE_B_LISTS {
    MMAP_DRIVE_B_FRAME_000_BIN = 0,        /*!< frame_000.bin */
    MMAP_DRIVE_B_FRAME_001_BIN = 1,        /*!< frame_001.bin */
    MMAP_DRIVE_B_FRAME_002_BIN = 2,        /*!< frame_002.bin */
    MMAP_DRIVE_B_FRAME_003_BIN = 3,        /*!< frame_003.bin */
    MMAP_DRIVE_B_FRAME_004_BIN = 4,        /*!< frame_004.bin */
    MMAP_DRIVE_B_FRAME_005_BIN = 5,        /*!< frame_005.bin */
    MMAP_DRIVE_B_FRAME_006_BIN = 6,        /*!< frame_006.bin */
    MMAP_DRIVE_B_FRAME_007_BIN = 7,        /*!< frame_007.bin */
    MMAP_DRIVE_B_FRAME_008_BIN = 8,        /*!< frame_008.bin */
    MMAP_DRIVE_B_FRAME_009_BIN = 9,        /*!< frame_009.bin */
};
