/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SPIFFS_ASSETS_FILES           72
#define MMAP_SPIFFS_ASSETS_CHECKSUM        0x6309

enum MMAP_SPIFFS_ASSETS_LISTS {
    MMAP_SPIFFS_ASSETS_CHILD0001_SQOI = 0,        /*!< child0001.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0002_SQOI = 1,        /*!< child0002.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0003_SQOI = 2,        /*!< child0003.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0004_SQOI = 3,        /*!< child0004.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0005_SQOI = 4,        /*!< child0005.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0006_SQOI = 5,        /*!< child0006.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0007_SQOI = 6,        /*!< child0007.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0008_SQOI = 7,        /*!< child0008.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0009_SQOI = 8,        /*!< child0009.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0010_SQOI = 9,        /*!< child0010.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0011_SQOI = 10,        /*!< child0011.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0012_SQOI = 11,        /*!< child0012.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0013_SQOI = 12,        /*!< child0013.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0014_SQOI = 13,        /*!< child0014.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0015_SQOI = 14,        /*!< child0015.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0016_SQOI = 15,        /*!< child0016.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0017_SQOI = 16,        /*!< child0017.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0018_SQOI = 17,        /*!< child0018.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0019_SQOI = 18,        /*!< child0019.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0020_SQOI = 19,        /*!< child0020.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0021_SQOI = 20,        /*!< child0021.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0022_SQOI = 21,        /*!< child0022.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD0023_SQOI = 22,        /*!< child0023.sqoi */
    MMAP_SPIFFS_ASSETS_CHILD_BG_SQOI = 23,        /*!< child_bg.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0001_SQOI = 24,        /*!< clean0001.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0002_SQOI = 25,        /*!< clean0002.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0003_SQOI = 26,        /*!< clean0003.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0004_SQOI = 27,        /*!< clean0004.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0005_SQOI = 28,        /*!< clean0005.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0006_SQOI = 29,        /*!< clean0006.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0007_SQOI = 30,        /*!< clean0007.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0008_SQOI = 31,        /*!< clean0008.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0009_SQOI = 32,        /*!< clean0009.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0010_SQOI = 33,        /*!< clean0010.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0011_SQOI = 34,        /*!< clean0011.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0012_SQOI = 35,        /*!< clean0012.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0013_SQOI = 36,        /*!< clean0013.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0014_SQOI = 37,        /*!< clean0014.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0015_SQOI = 38,        /*!< clean0015.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0016_SQOI = 39,        /*!< clean0016.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0017_SQOI = 40,        /*!< clean0017.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0018_SQOI = 41,        /*!< clean0018.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0019_SQOI = 42,        /*!< clean0019.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0020_SQOI = 43,        /*!< clean0020.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0021_SQOI = 44,        /*!< clean0021.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0022_SQOI = 45,        /*!< clean0022.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN0023_SQOI = 46,        /*!< clean0023.sqoi */
    MMAP_SPIFFS_ASSETS_CLEAN_BG_SQOI = 47,        /*!< clean_bg.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0001_SQOI = 48,        /*!< quick0001.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0002_SQOI = 49,        /*!< quick0002.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0003_SQOI = 50,        /*!< quick0003.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0004_SQOI = 51,        /*!< quick0004.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0005_SQOI = 52,        /*!< quick0005.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0006_SQOI = 53,        /*!< quick0006.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0007_SQOI = 54,        /*!< quick0007.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0008_SQOI = 55,        /*!< quick0008.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0009_SQOI = 56,        /*!< quick0009.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0010_SQOI = 57,        /*!< quick0010.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0011_SQOI = 58,        /*!< quick0011.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0012_SQOI = 59,        /*!< quick0012.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0013_SQOI = 60,        /*!< quick0013.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0014_SQOI = 61,        /*!< quick0014.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0015_SQOI = 62,        /*!< quick0015.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0016_SQOI = 63,        /*!< quick0016.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0017_SQOI = 64,        /*!< quick0017.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0018_SQOI = 65,        /*!< quick0018.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0019_SQOI = 66,        /*!< quick0019.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0020_SQOI = 67,        /*!< quick0020.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0021_SQOI = 68,        /*!< quick0021.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0022_SQOI = 69,        /*!< quick0022.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK0023_SQOI = 70,        /*!< quick0023.sqoi */
    MMAP_SPIFFS_ASSETS_QUICK_BG_SQOI = 71,        /*!< quick_bg.sqoi */
};
