/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_DRIVE_A_FILES           10
#define MMAP_DRIVE_A_CHECKSUM        0x93F1

enum MMAP_DRIVE_A_LISTS {
    MMAP_DRIVE_A_FRAME_000_SQOI = 0,        /*!< frame_000.sqoi */
    MMAP_DRIVE_A_FRAME_001_SQOI = 1,        /*!< frame_001.sqoi */
    MMAP_DRIVE_A_FRAME_002_SQOI = 2,        /*!< frame_002.sqoi */
    MMAP_DRIVE_A_FRAME_003_SQOI = 3,        /*!< frame_003.sqoi */
    MMAP_DRIVE_A_FRAME_004_SQOI = 4,        /*!< frame_004.sqoi */
    MMAP_DRIVE_A_FRAME_005_SQOI = 5,        /*!< frame_005.sqoi */
    MMAP_DRIVE_A_FRAME_006_SQOI = 6,        /*!< frame_006.sqoi */
    MMAP_DRIVE_A_FRAME_007_SQOI = 7,        /*!< frame_007.sqoi */
    MMAP_DRIVE_A_FRAME_008_SQOI = 8,        /*!< frame_008.sqoi */
    MMAP_DRIVE_A_FRAME_009_SQOI = 9,        /*!< frame_009.sqoi */
};
