// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Eletric_toothbrush

#include "ui.h"
#include "ui_helpers.h"
///////////////////// VARIABLES ////////////////////


// SCREEN: ui_systemstart_screen
void ui_systemstart_screen_init(void);
lv_obj_t * ui_systemstart_screen;
lv_obj_t * ui_systemstart_screen_imagelogo;


// SCREEN: ui_systemclose_screen
void ui_systemclose_screen_init(void);
lv_obj_t * ui_systemclose_screen;
lv_obj_t * ui_systemclose_screen_container1;
lv_obj_t * ui_systemclose_screen_imagepwroff;
lv_obj_t * ui_systemclose_screen_labelpwroff1;
lv_obj_t * ui_systemclose_screen_labelpwroff2;
lv_obj_t * ui_systemclose_screen_labelSysReset1;
lv_obj_t * ui_systemclose_screen_labelSysReset2;




// SCREEN: ui_home_screen
void ui_home_screen_init(void);
lv_obj_t * ui_home_screen;
lv_obj_t * ui_home_screen_container2;
lv_obj_t * ui_home_screen_imagewifi;
lv_obj_t * ui_home_screen_imagebt;
lv_obj_t * ui_home_screen_containermain;
lv_obj_t * ui_home_screen_containertime;
lv_obj_t * ui_home_screen_labeltimehour;
lv_obj_t * ui_home_screen_labeltimeseparator;
lv_obj_t * ui_home_screen_labeltimesec;
lv_obj_t * ui_home_screen_containerdata;
lv_obj_t * ui_home_screen_labeldate;
lv_obj_t * ui_home_screen_labelweek;
lv_obj_t * ui_home_screen_imagelogo;
lv_obj_t * ui_home_screen_containerpwr;
lv_obj_t * ui_home_screen_imagebattery;
lv_obj_t * ui_home_screen_labelpwr;


// SCREEN: ui_brushing_screen
void ui_brushing_screen_init(void);
lv_obj_t * ui_brushing_screen;
lv_obj_t * ui_brushing_screen_labelremaintime;
lv_obj_t * ui_brushing_screen_arcbrushtime;
lv_obj_t * ui_brushing_screen_imagestart;
lv_obj_t * ui_brushing_screen_label_prompt1;
lv_obj_t * ui_brushing_screen_label_prompt2;


// SCREEN: ui_evaluation_screen
void ui_evaluation_screen_init(void);
lv_obj_t * ui_evaluation_screen;
lv_obj_t * ui_evaluation_screen_labelremain;
lv_obj_t * ui_evaluation_screen_imagetooth;
lv_obj_t * ui_evaluation_screen_labelevalue;


// SCREEN: ui_charging_screen
void ui_charging_screen_init(void);
lv_obj_t * ui_charging_screen;
lv_obj_t * ui_charging_screen_arccharging;
lv_obj_t * ui_charging_screen_imagecharging;
lv_obj_t * ui_charging_screen_labelcharging;
lv_obj_t * ui____initial_actions0;

// const lv_img_dsc_t * ui_imgset_battery[1] = {&ui_img_battery8_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// SCREENS ////////////////////
lv_obj_t* ui_screen[6]; 
lv_disp_t * g_dispp;
static lv_theme_t * s_theme;
void ui_init(void)
{
    g_dispp = lv_disp_get_default();
    s_theme = lv_theme_default_init(g_dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(g_dispp, s_theme);
    ui_systemstart_screen_init();
    ui_systemclose_screen_init();
    ui_home_screen_init();
    ui_brushing_screen_init();
    ui_evaluation_screen_init();
    ui_charging_screen_init();

    ui_screen[0] = ui_systemstart_screen;
    ui_screen[1] = ui_home_screen;
    ui_screen[2] = ui_brushing_screen;
    ui_screen[3] = ui_evaluation_screen;
    ui_screen[4] = ui_charging_screen;
    ui_screen[5] = ui_systemclose_screen;
    
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_systemstart_screen);
}
