// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Eletric_toothbrush

#ifndef _ELETRIC_TOOTHBRUSH_UI_H
#define _ELETRIC_TOOTHBRUSH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
/**< Screen index point */
extern lv_obj_t* ui_screen[6]; 
// SCREEN: ui_systemstart_screen
void ui_systemstart_screen_init(void);
extern lv_obj_t * ui_systemstart_screen;
extern lv_obj_t * ui_systemstart_screen_imagelogo;
// SCREEN: ui_systemclose_screen
void ui_systemclose_screen_init(void);
extern lv_obj_t * ui_systemclose_screen;
extern lv_obj_t * ui_systemclose_screen_container1;
extern lv_obj_t * ui_systemclose_screen_imagepwroff;
extern lv_obj_t * ui_systemclose_screen_labelpwroff1;
extern lv_obj_t * ui_systemclose_screen_labelpwroff2;
extern lv_obj_t * ui_systemclose_screen_labelSysReset1;
extern lv_obj_t * ui_systemclose_screen_labelSysReset2;

// SCREEN: ui_home_screen
void ui_home_screen_init(void);
extern lv_obj_t * ui_home_screen;
extern lv_obj_t * ui_home_screen_container2;
extern lv_obj_t * ui_home_screen_imagewifi;
extern lv_obj_t * ui_home_screen_imagebt;
extern lv_obj_t * ui_home_screen_containermain;
extern lv_obj_t * ui_home_screen_containertime;
extern lv_obj_t * ui_home_screen_labeltimehour;
extern lv_obj_t * ui_home_screen_labeltimeseparator;
extern lv_obj_t * ui_home_screen_labeltimesec;
extern lv_obj_t * ui_home_screen_containerdata;
extern lv_obj_t * ui_home_screen_labeldate;
extern lv_obj_t * ui_home_screen_labelweek;
extern lv_obj_t * ui_home_screen_imagelogo;
extern lv_obj_t * ui_home_screen_containerpwr;
extern lv_obj_t * ui_home_screen_imagebattery;
extern lv_obj_t * ui_home_screen_labelpwr;
extern lv_obj_t*  ui_home_screen_battery_value;
#define BATTERY_FULL 30
extern char battery_value_str[15];

// SCREEN: ui_brushing_screen
void ui_brushing_screen_init(void);
extern lv_obj_t * ui_brushing_screen;
extern lv_obj_t * ui_brushing_screen_labelremaintime;
extern lv_obj_t * ui_brushing_screen_arcbrushtime;
extern lv_obj_t * ui_brushing_screen_imagestart;
extern lv_obj_t * ui_brushing_screen_label_prompt1;
extern lv_obj_t * ui_brushing_screen_label_prompt2;
extern char brushtooth_remain_time_str[20];

// SCREEN: ui_evaluation_screen
void ui_evaluation_screen_init(void);
extern lv_obj_t * ui_evaluation_screen;
extern lv_obj_t * ui_evaluation_screen_labelremain;
extern lv_obj_t * ui_evaluation_screen_imagetooth;
extern lv_obj_t * ui_evaluation_screen_labelevalue;

// SCREEN: ui_charging_screen
void ui_charging_screen_init(void);
extern lv_obj_t * ui_charging_screen;
extern lv_obj_t * ui_charging_screen_arccharging;
extern lv_obj_t * ui_charging_screen_imagecharging;
extern lv_obj_t * ui_charging_screen_labelcharging;
extern lv_obj_t * ui____initial_actions0;
extern char charging_value_str[10];

LV_IMG_DECLARE(ui_img_esplogo_png);    // assets/esplogo.png
LV_IMG_DECLARE(ui_img_power_off_png);    // assets/power_off.png
LV_IMG_DECLARE(ui_img_wifion_png);    // assets/wifion.png
LV_IMG_DECLARE(ui_img_bt_off_png);    // assets/bt_off.png
LV_IMG_DECLARE(ui_img_tooth_logox_png);    // assets/tooth_logox.png
LV_IMG_DECLARE(ui_img_battery8_png);    // assets/battery8.png
LV_IMG_DECLARE(ui_img_start_brush_icon_png);    // assets/start_brush_icon.png
LV_IMG_DECLARE(ui_img_effect1_png);    // assets/effect1.png
LV_IMG_DECLARE(ui_img_power_icon_png);    // assets/power_icon.png
LV_IMG_DECLARE(ui_img_bt_on_png);    // assets/bt_on.png
LV_IMG_DECLARE(ui_img_effect2_png);    // assets/effect2.png
LV_IMG_DECLARE(ui_img_effect3_png);    // assets/effect3.png
LV_IMG_DECLARE(ui_img_effect4_png);    // assets/effect4.png
LV_IMG_DECLARE(ui_img_wifioff_png);    // assets/wifioff.png
LV_IMG_DECLARE(ui_img_stop_brush_icon_png);    // assets/stop_brush_icon.png
LV_IMG_DECLARE(ui_img_effect0_png);    // assets/effect0.png
LV_IMG_DECLARE(ui_img_bat_container_png);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
