// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Eletric_toothbrush

#include <stdio.h>
#include "../ui.h"
#include "ui_main.h"

lv_obj_t* g_brush_strength_value[BRUSH_STRENTH_MAX];
static lv_obj_t* s_ui_startbrush_container;

brush_time_t time_format_conversion(brush_second_t brush_time); 
char brushtooth_remain_time_str[20]; /**< brushtooth remain time_str */
void ui_brushing_screen_init(void)
{
    ui_brushing_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_brushing_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_brushing_screen_labelremaintime = lv_label_create(ui_brushing_screen);
    lv_obj_set_x(ui_brushing_screen_labelremaintime, 0);
    lv_obj_set_y(ui_brushing_screen_labelremaintime, 15);
    lv_obj_set_align(ui_brushing_screen_labelremaintime, LV_ALIGN_CENTER);
    brush_time_t brush_time =  time_format_conversion((brush_second_t)get_brush_total_time());
    sprintf(brushtooth_remain_time_str, "%02d : %02d", (int)brush_time.brush_minute, (int)brush_time.brush_second);
    lv_label_set_text(ui_brushing_screen_labelremaintime, brushtooth_remain_time_str);
    lv_obj_set_style_text_font(ui_brushing_screen_labelremaintime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brushing_screen_arcbrushtime = lv_arc_create(ui_brushing_screen);
    lv_obj_set_width(ui_brushing_screen_arcbrushtime, 70);
    lv_obj_set_height(ui_brushing_screen_arcbrushtime, 70);
    lv_obj_set_x(ui_brushing_screen_arcbrushtime, 0);
    lv_obj_set_y(ui_brushing_screen_arcbrushtime, -35);
    lv_obj_set_align(ui_brushing_screen_arcbrushtime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_brushing_screen_arcbrushtime, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_brushing_screen_arcbrushtime, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_range(ui_brushing_screen_arcbrushtime, 0, 360);
    lv_arc_set_value(ui_brushing_screen_arcbrushtime, 360);
    lv_arc_set_rotation(ui_brushing_screen_arcbrushtime, 270);
    lv_arc_set_bg_angles(ui_brushing_screen_arcbrushtime, 0, 360);
    lv_arc_set_mode(ui_brushing_screen_arcbrushtime, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_width(ui_brushing_screen_arcbrushtime, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_style(ui_brushing_screen_arcbrushtime, NULL, LV_PART_KNOB);
    lv_obj_clear_flag(ui_brushing_screen_arcbrushtime, LV_OBJ_FLAG_CLICKABLE);  /*To not allow adjusting by click*/

    lv_obj_set_style_arc_color(ui_brushing_screen_arcbrushtime, lv_color_hex(0xDC143C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_brushing_screen_arcbrushtime, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_brushing_screen_arcbrushtime, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_brushing_screen_imagestart = lv_img_create(ui_brushing_screen_arcbrushtime);
    lv_img_set_src(ui_brushing_screen_imagestart, &ui_img_stop_brush_icon_png);
    lv_obj_set_width(ui_brushing_screen_imagestart, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_brushing_screen_imagestart, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_brushing_screen_imagestart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_brushing_screen_imagestart, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_brushing_screen_imagestart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_brushing_screen_label_prompt1 = lv_label_create(ui_brushing_screen);
    lv_obj_set_x(ui_brushing_screen_label_prompt1, 0);
    lv_obj_set_y(ui_brushing_screen_label_prompt1, 35);
    lv_obj_set_align(ui_brushing_screen_label_prompt1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brushing_screen_label_prompt1, "LongPre-Exit");
    lv_obj_set_style_text_color(ui_brushing_screen_label_prompt1, lv_color_hex(0xE12380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brushing_screen_label_prompt1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_brushing_screen_label_prompt1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brushing_screen_label_prompt2 = lv_label_create(ui_brushing_screen);
    lv_obj_set_x(ui_brushing_screen_label_prompt2, 0);
    lv_obj_set_y(ui_brushing_screen_label_prompt2, 50);
    lv_obj_set_align(ui_brushing_screen_label_prompt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brushing_screen_label_prompt2, "Single-Paused");
    lv_obj_set_style_text_color(ui_brushing_screen_label_prompt2, lv_color_hex(0x1095DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brushing_screen_label_prompt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_brushing_screen_label_prompt2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_ui_startbrush_container = lv_obj_create(ui_brushing_screen);
    lv_obj_remove_style_all(s_ui_startbrush_container);
    lv_obj_set_width(s_ui_startbrush_container, 80);
    lv_obj_set_height(s_ui_startbrush_container, 12);
    lv_obj_set_x(s_ui_startbrush_container, 0);
    lv_obj_set_y(s_ui_startbrush_container, 65);
    lv_obj_set_align(s_ui_startbrush_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(s_ui_startbrush_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(s_ui_startbrush_container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(s_ui_startbrush_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(s_ui_startbrush_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(s_ui_startbrush_container, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    for (int i = 0; i < BRUSH_STRENTH_MAX; ++i) {
        g_brush_strength_value[i] = lv_obj_create(s_ui_startbrush_container);
        lv_obj_set_width(g_brush_strength_value[i], 6);
        lv_obj_set_height(g_brush_strength_value[i], 6);
        lv_obj_set_x(g_brush_strength_value[i], -25);
        lv_obj_set_y(g_brush_strength_value[i], 70);
        lv_obj_set_align(g_brush_strength_value[i], LV_ALIGN_CENTER);
        lv_obj_clear_flag(g_brush_strength_value[i], LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_bg_color(g_brush_strength_value[i], lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(g_brush_strength_value[i], 50, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(g_brush_strength_value[i], lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_opa(g_brush_strength_value[i], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    brush_strength_init();
}
