// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Eletric_toothbrush

#include "../ui.h"
#include "gui/ui_main.h"
#include <stdio.h>


static void tooth_logo_img_anim_cb(void* var, int32_t v)
{
    lv_obj_set_y(var, v);
}

static void labeltimeseparator_anim_cb(void* var, int32_t v)
{
    lv_obj_set_style_text_opa(var, v, 0);
}

char battery_value_str[15]; /**< power label str */
lv_obj_t* ui_home_screen_battery_value;
void ui_home_screen_init(void)
{
    ui_home_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_home_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_home_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_home_screen, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_container2 = lv_obj_create(ui_home_screen);
    lv_obj_remove_style_all(ui_home_screen_container2);
    lv_obj_set_width(ui_home_screen_container2, 70);
    lv_obj_set_height(ui_home_screen_container2, 20);
    lv_obj_set_x(ui_home_screen_container2, 1);
    lv_obj_set_y(ui_home_screen_container2, -70);
    lv_obj_set_align(ui_home_screen_container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_home_screen_container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_home_screen_container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_home_screen_container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_home_screen_container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_home_screen_container2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_imagewifi = lv_img_create(ui_home_screen_container2);
    lv_img_set_src(ui_home_screen_imagewifi, &ui_img_wifion_png);
    lv_obj_set_width(ui_home_screen_imagewifi, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_home_screen_imagewifi, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_home_screen_imagewifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_home_screen_imagewifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_home_screen_imagewifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home_screen_imagebt = lv_img_create(ui_home_screen_container2);
    lv_img_set_src(ui_home_screen_imagebt, &ui_img_bt_off_png);
    lv_obj_set_width(ui_home_screen_imagebt, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_home_screen_imagebt, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_home_screen_imagebt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_home_screen_imagebt, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_home_screen_imagebt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home_screen_containermain = lv_obj_create(ui_home_screen);
    lv_obj_remove_style_all(ui_home_screen_containermain);
    lv_obj_set_width(ui_home_screen_containermain, 80);
    lv_obj_set_height(ui_home_screen_containermain, 40);
    lv_obj_set_x(ui_home_screen_containermain, 0);
    lv_obj_set_y(ui_home_screen_containermain, -35);
    lv_obj_set_align(ui_home_screen_containermain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_home_screen_containermain, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_home_screen_containermain, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_home_screen_containermain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_home_screen_containermain, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_home_screen_containermain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_containertime = lv_obj_create(ui_home_screen_containermain);
    lv_obj_remove_style_all(ui_home_screen_containertime);
    lv_obj_set_width(ui_home_screen_containertime, 80);
    lv_obj_set_height(ui_home_screen_containertime, 20);
    lv_obj_set_align(ui_home_screen_containertime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_home_screen_containertime, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_home_screen_containertime, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_home_screen_containertime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home_screen_labeltimehour = lv_label_create(ui_home_screen_containertime);
    lv_obj_set_width(ui_home_screen_labeltimehour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_home_screen_labeltimehour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_home_screen_labeltimehour, -23);
    lv_obj_set_y(ui_home_screen_labeltimehour, -99);
    lv_obj_set_align(ui_home_screen_labeltimehour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_home_screen_labeltimehour, "10");
    lv_obj_set_style_text_font(ui_home_screen_labeltimehour, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_labeltimeseparator = lv_label_create(ui_home_screen_containertime);
    lv_obj_set_width(ui_home_screen_labeltimeseparator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_home_screen_labeltimeseparator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_home_screen_labeltimeseparator, -23);
    lv_obj_set_y(ui_home_screen_labeltimeseparator, -99);
    lv_obj_set_align(ui_home_screen_labeltimeseparator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_home_screen_labeltimeseparator, " : ");
    lv_obj_set_style_text_font(ui_home_screen_labeltimeseparator, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_anim_t labeltimeseparator_anim;
    lv_anim_init(&labeltimeseparator_anim);
    lv_anim_set_var(&labeltimeseparator_anim, ui_home_screen_labeltimeseparator);
    lv_anim_set_values(&labeltimeseparator_anim, 0, 255);
    lv_anim_set_time(&labeltimeseparator_anim, 1000);
    lv_anim_set_path_cb(&labeltimeseparator_anim, lv_anim_path_step);
    lv_anim_set_exec_cb(&labeltimeseparator_anim, labeltimeseparator_anim_cb);
    lv_anim_set_playback_delay(&labeltimeseparator_anim, 0);
    lv_anim_set_playback_time(&labeltimeseparator_anim, 1000);
    lv_anim_set_repeat_delay(&labeltimeseparator_anim, 0);
    lv_anim_set_repeat_count(&labeltimeseparator_anim, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&labeltimeseparator_anim);

    ui_home_screen_labeltimesec = lv_label_create(ui_home_screen_containertime);
    lv_obj_set_width(ui_home_screen_labeltimesec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_home_screen_labeltimesec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_home_screen_labeltimesec, -23);
    lv_obj_set_y(ui_home_screen_labeltimesec, -99);
    lv_obj_set_align(ui_home_screen_labeltimesec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_home_screen_labeltimesec, "14");
    lv_obj_set_style_text_font(ui_home_screen_labeltimesec, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);




    // ui_home_screen_labeltime = lv_label_create(ui_home_screen_containermain);
    // lv_obj_set_width(ui_home_screen_labeltime, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_home_screen_labeltime, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_home_screen_labeltime, 1);
    // lv_obj_set_y(ui_home_screen_labeltime, -99);
    // lv_obj_set_align(ui_home_screen_labeltime, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_home_screen_labeltime, "11 : 51");
    // lv_obj_set_style_text_font(ui_home_screen_labeltime, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_containerdata = lv_obj_create(ui_home_screen_containermain);
    lv_obj_remove_style_all(ui_home_screen_containerdata);
    lv_obj_set_width(ui_home_screen_containerdata, 70);
    lv_obj_set_height(ui_home_screen_containerdata, 15);
    lv_obj_set_x(ui_home_screen_containerdata, 0);
    lv_obj_set_y(ui_home_screen_containerdata, 2);
    lv_obj_set_align(ui_home_screen_containerdata, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_home_screen_containerdata, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_home_screen_containerdata, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_home_screen_containerdata, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_home_screen_containerdata, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_home_screen_containerdata, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_labeldate = lv_label_create(ui_home_screen_containerdata);
    lv_obj_set_width(ui_home_screen_labeldate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_home_screen_labeldate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_home_screen_labeldate, -25);
    lv_obj_set_y(ui_home_screen_labeldate, 2);
    lv_obj_set_align(ui_home_screen_labeldate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_home_screen_labeldate, "07/31");
    lv_obj_set_style_text_font(ui_home_screen_labeldate, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_labelweek = lv_label_create(ui_home_screen_containerdata);
    lv_obj_set_width(ui_home_screen_labelweek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_home_screen_labelweek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_home_screen_labelweek, 28);
    lv_obj_set_y(ui_home_screen_labelweek, -2);
    lv_obj_set_align(ui_home_screen_labelweek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_home_screen_labelweek, "Wed");
    lv_obj_set_style_text_font(ui_home_screen_labelweek, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_imagelogo = lv_img_create(ui_home_screen);
    lv_img_set_src(ui_home_screen_imagelogo, &ui_img_tooth_logox_png);
    lv_obj_set_width(ui_home_screen_imagelogo, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_home_screen_imagelogo, LV_SIZE_CONTENT);    /// 47
    lv_obj_set_x(ui_home_screen_imagelogo, 0);
    lv_obj_set_y(ui_home_screen_imagelogo, 20);
    lv_obj_set_align(ui_home_screen_imagelogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_home_screen_imagelogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_home_screen_imagelogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_anim_t tooth_logo_image_anim;
    lv_anim_init(&tooth_logo_image_anim);
    lv_anim_set_var(&tooth_logo_image_anim, ui_home_screen_imagelogo);
    lv_anim_set_values(&tooth_logo_image_anim, 15, 25);
    lv_anim_set_time(&tooth_logo_image_anim, 500);
    lv_anim_set_path_cb(&tooth_logo_image_anim, lv_anim_path_ease_in_out);
    lv_anim_set_exec_cb(&tooth_logo_image_anim, tooth_logo_img_anim_cb);
    lv_anim_set_playback_delay(&tooth_logo_image_anim, 10);
    lv_anim_set_playback_time(&tooth_logo_image_anim, 500);
    lv_anim_set_repeat_delay(&tooth_logo_image_anim, 0);
    lv_anim_set_repeat_count(&tooth_logo_image_anim, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&tooth_logo_image_anim);

    ui_home_screen_containerpwr = lv_obj_create(ui_home_screen);
    lv_obj_remove_style_all(ui_home_screen_containerpwr);
    lv_obj_set_width(ui_home_screen_containerpwr, 75);
    lv_obj_set_height(ui_home_screen_containerpwr, 15);
    lv_obj_set_x(ui_home_screen_containerpwr, 0);
    lv_obj_set_y(ui_home_screen_containerpwr, 65);
    lv_obj_set_align(ui_home_screen_containerpwr, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_home_screen_containerpwr, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_home_screen_containerpwr, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_home_screen_containerpwr, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_home_screen_containerpwr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_home_screen_containerpwr, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**< battery value display */
    ui_home_screen_battery_value = lv_obj_create(ui_home_screen);
    lv_obj_set_style_radius(ui_home_screen_battery_value, 0, 0);
    lv_obj_set_style_outline_width(ui_home_screen_battery_value, 0, 0);
    lv_obj_set_style_outline_pad(ui_home_screen_battery_value, 0, 0);
    lv_obj_set_style_border_width(ui_home_screen_battery_value, 0, 0);
    lv_obj_set_height(ui_home_screen_battery_value, 17);
    lv_obj_set_x(ui_home_screen_battery_value, 23);
    lv_obj_set_y(ui_home_screen_battery_value, 65);
    lv_obj_set_style_bg_color(ui_home_screen_battery_value, lv_color_hex(0x00468B), 0);
    lv_obj_set_align(ui_home_screen_battery_value, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_home_screen_battery_value, LV_OBJ_FLAG_SCROLLABLE); 
    lv_obj_set_width(ui_home_screen_battery_value, BATTERY_FULL);

    ui_home_screen_imagebattery = lv_img_create(ui_home_screen);
    lv_img_set_src(ui_home_screen_imagebattery, &ui_img_bat_container_png);
    lv_obj_set_width(ui_home_screen_imagebattery, LV_SIZE_CONTENT);   /// 38
    lv_obj_set_height(ui_home_screen_imagebattery, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_home_screen_imagebattery, -2);
    lv_obj_set_y(ui_home_screen_imagebattery, 65);
    lv_obj_set_align(ui_home_screen_imagebattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_home_screen_imagebattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_home_screen_imagebattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home_screen_labelpwr = lv_label_create(ui_home_screen);
    lv_obj_set_width(ui_home_screen_labelpwr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_home_screen_labelpwr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_home_screen_labelpwr, -4);
    lv_obj_set_y(ui_home_screen_labelpwr, 65);
    lv_obj_set_align(ui_home_screen_labelpwr, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_home_screen_labelpwr, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_home_screen_labelpwr, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_home_screen_labelpwr, "100%");
    lv_obj_set_style_text_font(ui_home_screen_labelpwr, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
}
