// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Eletric_toothbrush

#include "../ui.h"

static lv_obj_t * s_ui_systemclose_screen_panel;

void ui_systemclose_screen_init(void)
{
    ui_systemclose_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_systemclose_screen, LV_OBJ_FLAG_SCROLLABLE);

    s_ui_systemclose_screen_panel = lv_obj_create(ui_systemclose_screen);
    lv_obj_set_width(s_ui_systemclose_screen_panel, 60);
    lv_obj_set_height(s_ui_systemclose_screen_panel, 60);
    lv_obj_set_x(s_ui_systemclose_screen_panel, 0);
    lv_obj_set_y(s_ui_systemclose_screen_panel, -25);
    lv_obj_set_align(s_ui_systemclose_screen_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(s_ui_systemclose_screen_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(s_ui_systemclose_screen_panel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemclose_screen_imagepwroff = lv_img_create(ui_systemclose_screen);
    lv_img_set_src(ui_systemclose_screen_imagepwroff, &ui_img_power_off_png);
    lv_obj_set_width(ui_systemclose_screen_imagepwroff, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_systemclose_screen_imagepwroff, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_systemclose_screen_imagepwroff, 0);
    lv_obj_set_y(ui_systemclose_screen_imagepwroff, -25);
    lv_obj_set_align(ui_systemclose_screen_imagepwroff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_systemclose_screen_imagepwroff, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_systemclose_screen_imagepwroff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_systemclose_screen_labelpwroff1 = lv_label_create(ui_systemclose_screen);
    lv_obj_set_width(ui_systemclose_screen_labelpwroff1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemclose_screen_labelpwroff1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemclose_screen_labelpwroff1, 0);
    lv_obj_set_y(ui_systemclose_screen_labelpwroff1, 20);
    lv_obj_set_align(ui_systemclose_screen_labelpwroff1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemclose_screen_labelpwroff1, "LongPress:");
    lv_obj_set_style_text_color(ui_systemclose_screen_labelpwroff1, lv_color_hex(0x1095DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemclose_screen_labelpwroff1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemclose_screen_labelpwroff1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemclose_screen_labelpwroff2 = lv_label_create(ui_systemclose_screen);
    lv_obj_set_width(ui_systemclose_screen_labelpwroff2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemclose_screen_labelpwroff2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemclose_screen_labelpwroff2, 0);
    lv_obj_set_y(ui_systemclose_screen_labelpwroff2, 35);
    lv_obj_set_align(ui_systemclose_screen_labelpwroff2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemclose_screen_labelpwroff2, "Reset");
    lv_obj_set_style_text_color(ui_systemclose_screen_labelpwroff2, lv_color_hex(0x1095DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemclose_screen_labelpwroff2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemclose_screen_labelpwroff2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemclose_screen_labelSysReset1 = lv_label_create(ui_systemclose_screen);
    lv_obj_set_width(ui_systemclose_screen_labelSysReset1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemclose_screen_labelSysReset1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemclose_screen_labelSysReset1, 0);
    lv_obj_set_y(ui_systemclose_screen_labelSysReset1, 55);
    lv_obj_set_align(ui_systemclose_screen_labelSysReset1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemclose_screen_labelSysReset1, "SingleClick:");
    lv_obj_set_style_text_color(ui_systemclose_screen_labelSysReset1, lv_color_hex(0xE12380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemclose_screen_labelSysReset1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemclose_screen_labelSysReset1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemclose_screen_labelSysReset2 = lv_label_create(ui_systemclose_screen);
    lv_obj_set_width(ui_systemclose_screen_labelSysReset2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemclose_screen_labelSysReset2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemclose_screen_labelSysReset2, 0);
    lv_obj_set_y(ui_systemclose_screen_labelSysReset2, 70);
    lv_obj_set_align(ui_systemclose_screen_labelSysReset2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemclose_screen_labelSysReset2, "Power OFF");
    lv_obj_set_style_text_color(ui_systemclose_screen_labelSysReset2, lv_color_hex(0xE12380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemclose_screen_labelSysReset2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemclose_screen_labelSysReset2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
