// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Eletric_toothbrush

#include "../ui.h"
#include "gui/ui_main.h"

static lv_anim_timeline_t* s_anim_timeline = NULL;
static lv_anim_t logo_image_opa1_anim;
static lv_anim_t logo_image_bounce_anim;
static lv_anim_t logo_image_opa_shallow_anim;

static lv_style_t s_img_style;
static void logo_img_opa1_anim_cb(void* var, int32_t v)
{
    lv_obj_set_style_img_opa(var, v, 0);
}
static void logo_image_opa_shallow_anim_cb(void* var, int32_t v)
{
    lv_obj_set_style_img_opa(var, v, 0);
}

static void logo_img_y_anim_cb(void* var, int32_t v)
{
    lv_obj_set_y(var, v);
}

static void animation_finish_cb(void) 
{
    ui_change_to_screen(HOME_SCREEN_INDEX);
    lv_anim_timeline_del(s_anim_timeline);
    s_anim_timeline = NULL;
    lv_anim_del(&logo_image_opa1_anim, logo_img_opa1_anim_cb);
    lv_anim_del(&logo_image_bounce_anim, logo_img_y_anim_cb);
    lv_anim_del(&logo_image_opa_shallow_anim, logo_image_opa_shallow_anim_cb);
    lv_obj_del(ui_systemstart_screen);
    ui_systemstart_screen = NULL;
}

void ui_systemstart_screen_init(void)
{
    ui_systemstart_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_systemstart_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_systemstart_screen_imagelogo = lv_img_create(ui_systemstart_screen);
    lv_img_set_src(ui_systemstart_screen_imagelogo, &ui_img_esplogo_png);
    lv_obj_set_width(ui_systemstart_screen_imagelogo, LV_SIZE_CONTENT);   /// 69
    lv_obj_set_height(ui_systemstart_screen_imagelogo, LV_SIZE_CONTENT);    /// 63
    lv_obj_set_align(ui_systemstart_screen_imagelogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_systemstart_screen_imagelogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_systemstart_screen_imagelogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_style_init(&s_img_style);
    lv_style_set_img_opa(&s_img_style, 255);
    lv_obj_add_style(ui_systemstart_screen_imagelogo, &s_img_style, 0);

    lv_anim_init(&logo_image_opa1_anim);
    lv_anim_set_var(&logo_image_opa1_anim, ui_systemstart_screen_imagelogo);
    lv_anim_set_values(&logo_image_opa1_anim, 0, 255);
    lv_anim_set_time(&logo_image_opa1_anim, 2000);
    lv_anim_set_path_cb(&logo_image_opa1_anim, lv_anim_path_ease_in_out);
    lv_anim_set_exec_cb(&logo_image_opa1_anim, logo_img_opa1_anim_cb);

    lv_anim_init(&logo_image_bounce_anim);
    lv_anim_set_var(&logo_image_bounce_anim, ui_systemstart_screen_imagelogo);
    lv_anim_set_values(&logo_image_bounce_anim, -5, 5);
    lv_anim_set_time(&logo_image_bounce_anim, 1000);
    lv_anim_set_path_cb(&logo_image_bounce_anim, lv_anim_path_ease_in_out);
    lv_anim_set_exec_cb(&logo_image_bounce_anim, logo_img_y_anim_cb);
    lv_anim_set_playback_delay(&logo_image_bounce_anim, 0);
    lv_anim_set_playback_time(&logo_image_bounce_anim, 1000);
    lv_anim_set_repeat_delay(&logo_image_bounce_anim, 0);
    lv_anim_set_repeat_count(&logo_image_bounce_anim, 1);

    lv_anim_init(&logo_image_opa_shallow_anim);
    lv_anim_set_var(&logo_image_opa_shallow_anim, ui_systemstart_screen_imagelogo);
    lv_anim_set_values(&logo_image_opa_shallow_anim, 255, 50);
    lv_anim_set_time(&logo_image_opa_shallow_anim, 500);
    lv_anim_set_path_cb(&logo_image_opa_shallow_anim, lv_anim_path_ease_in_out);
    lv_anim_set_exec_cb(&logo_image_opa_shallow_anim, logo_image_opa_shallow_anim_cb);

    lv_anim_set_ready_cb(&logo_image_opa_shallow_anim, (lv_anim_ready_cb_t)animation_finish_cb);
    s_anim_timeline = lv_anim_timeline_create();
    lv_anim_timeline_add(s_anim_timeline, 0, &logo_image_opa1_anim);
    lv_anim_timeline_add(s_anim_timeline, 0, &logo_image_bounce_anim);
    lv_anim_timeline_add(s_anim_timeline, 3000, &logo_image_opa_shallow_anim);
    lv_anim_timeline_start(s_anim_timeline);
}
